#!/bin/zsh

export RECOMBINEX_HOME="/Users/kaldiraz/Documents/recombinex_for_mac"
export BUILD_DIR="$RECOMBINEX_HOME/build"
export VENV_DIR="$BUILD_DIR/conda/envs/recombinex_venv/bin"
export SRA_DIR="$BUILD_DIR/sratoolkit.3.1.1-mac-x86_64/bin"
export SAMTOOLS_DIR="$BUILD_DIR/samtools-1.21"
export WINDOWMASKER_DIR="$BUILD_DIR/ncbi-blast-2.2.31+/bin"
export UCSC_DIR="$BUILD_DIR/UCSC_Utilities"
export BEDTOOLS="$VENV_DIR/bedtools"
export GEMTOOLS_DIR="$BUILD_DIR/gemtools-1.7.1-i3/bin"
export TRIMMOMATIC="$BUILD_DIR/Trimmomatic-0.39"
export JAVA_DIR="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin"
export PICARD_DIR="$BUILD_DIR/Picard-v2.19.0"
export BWA_DIR="$BUILD_DIR/bwa-0.7.18"
export GATK3="$BUILD_DIR/GATK3"
export FREEC="$BUILD_DIR/FREEC-11.6b"
